DEBUG tests/libex29_tests.c:65: ----- RUNNING: ./tests/libex29_tests
DEBUG tests/libex29_tests.c:57: 
----- test_dlopen
DEBUG tests/libex29_tests.c:58: 
----- test_functions
DEBUG tests/libex29_tests.c:59: 
----- test_failures
[ERROR] (tests/libex29_tests.c:14: errno: None) Function fail_on_purpose return 1 for data: Hello
[ERROR] (tests/libex29_tests.c:40: errno: None) fail_on_purpose failed.
